### PR TITLE
Upgrade golang version to 1.17 per u-root requirement

### PR DESCRIPTION
**Pull request by vejmarie**
Signed-off-by: Jean-Marie Verdun <jean-marie.verdun@hpe.com>

### CODE REVIEW

**Review by arunkoshy — APPROVED** [review]
have tested and also getting @susmithp to do a build_all check

**Comment by arunkoshy** [comment]
@susmithp can you please do a build_all.sh check on this PR.

**Comment by susmithp** [comment]
> @susmithp can you please do a build_all.sh check on this PR.

@arunkoshy I have tested it. build process works fine.

**Comment by arunkoshy** [comment]
thanks @susmithp

**Pull request merged**
