### PR TITLE
Added changes to handle the Url redirection

### PR DESCRIPTION
**Pull request by susmithp**

### CODE REVIEW

**Review by arunkoshy — CHANGES_REQUESTED** [review]
Shouldn't check the check be  (uri.indexOf("?") != -1) ? on 917 and 946 - happy to re-test post mod @susmithp ( kind ref : @vejmarie  )

**Comment by susmithp** [comment]
@arunkoshy I have made the changes. Please review.

**Review by arunkoshy — APPROVED** [review]
@vejmarie this LGTM now. Thanks, @susmithp  .. will merge after JM's sign-off and testing.

**Comment by arunkoshy** [comment]
@vejmarie this has been tested including the changes. Will merge once you sign off.

**Pull request merged**
