### PR TITLE
Fix for "Connection reset" reverse proxy error with BMC web

### PR DESCRIPTION
**Pull request by susmithp**
1. Creating the reverse proxy only once and reusing it for every request. 
2. Increased the "MaxIdleConnsPerHost" to 100, otherwise default was 2.

### CODE REVIEW

**Review by arunkoshy — CHANGES_REQUESTED** [review]
@susmithp as discussed offline regarding the specific build for osfci.tech - rest LGTM

**Comment by susmithp** [comment]
> @susmithp as discussed offline regarding the specific build for osfci.tech - rest LGTM

@arunkoshy I have made the correction.

**Review by arunkoshy — APPROVED** [review]
@susmithp LGTM ! we will merge in the order discussed with @DragonCoderz and after rollout to public.

**Review by arunkoshy — APPROVED** [review]
@susmithp LGTM ! we will merge in the order discussed with @DragonCoderz and after rollout to public.

**Pull request merged**
